dailyfresh/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add$',views.CartAddView.as_view(),name='add'),  #购物车记录添加
    url(r'^count$',views.CartCountView.as_view(),name='count'),  #异步请求购物车商品数量
    url(r'^info$', views.CartInfoView.as_view(), name='info'),  # 购物车页面显示
    url(r'^update$', views.CartUpdateView.as_view(), name='update'),  # 购物车记录更新
    url(r'^delete$', views.CartDeleteView.as_view(), name='delete'),  # 购物车记录删除
]

dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),                #后台管理模块
    url(r'^user/', include('user.urls', namespace='user')),   #用户模块
    url(r'^', include('goods.urls', namespace='goods')),      #首页模块
    url(r'^tinymce/', include('tinymce.urls')),               #tinymce
    url(r'^search/', include('haystack.urls')),               # haystack
    url(r'^cart/', include('cart.urls', namespace='cart')),   #购物车模块
    url(r'^order/', include('order.urls', namespace='order')),   #订单页面模块
]

dailyfresh/goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^$',views.index,name='index'),
    url(r'^index$',views.IndexView.as_view(),name='index'),  #首页
    url(r'^goods/(?P<goods_id>\d+)$',views.DetailView.as_view(),name='detail'), #详情页   #?P<value>的意思就是命名一个名字为value的组，匹配规则符合后面的\d+
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$',views.ListView.as_view(),name='list'), #列表页

]

dailyfresh/templates/search/search.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-商品列表</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_info fl">
					欢迎您：<em>张 山</em>
				</div>
				<div class="login_btn fl">
					<a href="login.html">登录</a>
					<span>|</span>
					<a href="register.html">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="user_center_info.html">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>
	</div>

	<div class="search_bar clearfix">
		<a href="/index" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<form action="/search" method="get">
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品" value="{{ query }}">
				<input type="button" class="input_btn fr" name="" value="搜索">
			</form>
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
					{% for type in types %}
					   <li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
					{% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="#">{{ query }}</a>
		<span>></span>
		<a href="#">搜索结果如下</a>
	</div>

	<div class="main_wrap clearfix">
			<ul class="goods_type_list clearfix">
				{% for i in page %}
				<li>
					<a href="{% url 'goods:detail' i.object.id %}"><img src="{{ i.object.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' i.object.id %}">{{ i.object.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ i.object.price }}</span>
						<span class="unit">{{ i.object.price }}/{{ i.object.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor %}
			</ul>

			<div class="pagenation">
				{% if page.has_previous %}
				<a href="/search?q={{ query }}&page={{ page.previous_page_number }}">上一页</a>
				{% endif %}
				<!--<a href="#" class="active">1</a>-->
				<!--<a href="#">2</a>-->
				{% for pindex in paginator.page_range %}
				   {% if pindex == page.number %}
				       <a href="/search?q={{ query }}&page={{ pindex }}" class="active">{{ pindex }}</a>
				   {% else %}
				       <a href="/search?q={{ query }}&page={{ pindex }}" >{{ pindex }}</a>
				   {% endif %}
				{% endfor %}
				{% if page.has_next %}
				<a href="/search?q={{ query }}&page={{ page.next_page_number }}">下一页</a>
                {% endif %}
		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>

    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript">
		$(function () {
			$.get(
			    '{% url "cart:count" %}',
				function (data) {
					$('#show_count').text(data.total_count)
                }
			)
        })
	</script>

</body>
</html>

dailyfresh/templates/search/search2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  搜索的换尖子{{ query }} <br/>
  当前页的Page对象：{{ page }} <br/>
  <ul>
      {% for i in page %}
         <li>{{ i.object }}</li>
      {% endfor %}
  </ul>
分页的paginator对象：{{ paginator }} <br/>
</body>
</html>