dailyfresh/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add$',views.CartAddView.as_view(),name='add'),  #购物车记录添加
    url(r'^count$',views.CartCountView.as_view(),name='count'),  #异步请求购物车商品数量
    url(r'^info$', views.CartInfoView.as_view(), name='info'),  # 购物车页面显示
    url(r'^update$', views.CartUpdateView.as_view(), name='update'),  # 购物车记录更新
    url(r'^delete$', views.CartDeleteView.as_view(), name='delete'),  # 购物车记录删除
]

dailyfresh/dailyfresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),                #后台管理模块
    url(r'^user/', include('user.urls', namespace='user')),   #用户模块
    url(r'^', include('goods.urls', namespace='goods')),      #首页模块
    url(r'^tinymce/', include('tinymce.urls')),               #tinymce
    url(r'^search/', include('haystack.urls')),               # haystack
    url(r'^cart/', include('cart.urls', namespace='cart')),   #购物车模块
    url(r'^order/', include('order.urls', namespace='order')),   #订单页面模块
]

dailyfresh/goods/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    #url(r'^$',views.index,name='index'),
    url(r'^index$',views.IndexView.as_view(),name='index'),  #首页
    url(r'^goods/(?P<goods_id>\d+)$',views.DetailView.as_view(),name='detail'), #详情页   #?P<value>的意思就是命名一个名字为value的组，匹配规则符合后面的\d+
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$',views.ListView.as_view(),name='list'), #列表页

]

dailyfresh/order/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^place$',views.OrderPlaceView.as_view(),name='place'),  #提交订单页面显示
    url(r'^commit$',views.OrderCommitView.as_view(),name='commit'),  #订单创建
    url(r'^pay$',views.OrderPayView.as_view(),name='pay'),  #订单支付
    url(r'^check$',views.CheckPayView.as_view(),name='check'),  #查询支付结果
]

dailyfresh/user/urls.py
from django.conf.urls import url
from user import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^register$',views.RegisterView.as_view(),name='register'),#用户注册
    url(r'^login$',views.LoginView.as_view(),name='login'),#用户登录
    url(r'^loginout$',views.loginout,name='loginout'),#退出登录
    url(r'^change_passwd$', views.Change_passwdView.as_view(), name='change_passwd'),#修改密码
    url(r'^validate_code$',views.validate_code,name='validate_code'),#验证码
    url(r'^active/(?P<token>.*)$', views.ActiveView.as_view(), name='active'),#用户激活

    #'''利用装饰器判定登录-方法1 (推荐)'''
    url(r'^$', views.UserInfoView.as_view(), name='user'), # 用户中心-信息页
    url(r'^order/(?P<page>\d+)$', views.UserOrderView.as_view(), name='order'),  # 用户中心-订单页  #?P<value>的意思就是命名一个名字为value的组，匹配规则符合后面的\d+
    url(r'^address$', views.UserAddressView.as_view(), name='address'),  # 用户中心-地址页

    #'''利用装饰器判定登录-方法2'''
    # url(r'^$', login_required(views.UserInfoView.as_view()), name='user'), # 用户中心-信息页
    # url(r'^order$', login_required(views.UserOrderView.as_view()), name='order'),  # 用户中心-订单页
    # url(r'^address$', login_required(views.UserAddressView.as_view()), name='address'),  # 用户中心-地址页

    #''省市县三级联动'''
    url(r'^get_all_province$', views.get_all_province, name='get_all_province'),
    url(r'^get_city_by_pid$', views.get_city_by_pid, name='get_city_by_pid'),
    url(r'^get_area_by_cid$', views.get_area_by_cid, name='get_area_by_cid'),

]

dailyfresh/cart/models.py
from django.db import models

dailyfresh/goods/models.py
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField

class GoodsType(BaseModel):
    '''商品类型模型类'''
    name = models.CharField(max_length=20, verbose_name='种类名称')
    logo = models.CharField(max_length=20, verbose_name='标识')
    image = models.ImageField(upload_to='type', verbose_name='商品类型图片')

    class Meta:
        db_table='df_user_type'
        verbose_name='商品种类'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.name

class GoodsSKU(BaseModel):
    '''商品SKU模型类'''
    status_choices=(
        (0,'上线'),
        (1,'下线'),
    )
    type = models.ForeignKey('GoodsType',verbose_name='商品种类')
    goods = models.ForeignKey('Goods',verbose_name='商品SPU')
    name = models.CharField(max_length=20, verbose_name='商品名称')
    desc = models.CharField(max_length=256, verbose_name='商品简介')
    price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='商品价格')
    unite = models.CharField(max_length=20, verbose_name='商品单位')
    image = models.ImageField(upload_to='goods', verbose_name='商品图片')
    stock=models.IntegerField(default=1,verbose_name='商品库存')
    sales = models.IntegerField(default=0,verbose_name='商品销量')
    status=models.SmallIntegerField(default=1,choices=status_choices,verbose_name='商品状态')

    class Meta:
        db_table='df_goods_sku'
        verbose_name='商品SKU'
        verbose_name_plural=verbose_name


    def __str__(self):
        return self.name

class Goods(BaseModel):
    '''商品SPU模型类'''
    name = models.CharField(max_length=20, verbose_name='商品SPU名称')
    #富文本类型：带有格式的文本
    detail = HTMLField(blank=True,verbose_name='商品详情')

    class Meta:
        db_table = 'df_goods'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsImage(BaseModel):
    '''商品图片模型类'''
    sku = models.ForeignKey('GoodsSKU', verbose_name='商品')
    image = models.ImageField(upload_to='goods', verbose_name='图片路径')

    class Meta:
        db_table = 'df_goods_image'
        verbose_name = '商品图片'
        verbose_name_plural = verbose_name


class IndexGoodsBanner(BaseModel):
    '''首页轮播商品展示模型类'''
    sku = models.ForeignKey('GoodsSKU', verbose_name='商品')
    image = models.ImageField(upload_to='banner', verbose_name='图片')
    index=models.SmallIntegerField(default=0,verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_banner'
        verbose_name = '首页轮播商品'
        verbose_name_plural = verbose_name


class IndePromotionBanner(BaseModel):
    '''首页促销活动模型类'''
    name = models.CharField(max_length=20, verbose_name='活动名称')
    #url=models.URLField(verbose_name='活动链接')
    url=models.CharField(max_length=256,verbose_name='活动链接')
    image = models.ImageField(upload_to='banner', verbose_name='活动图片')
    index=models.SmallIntegerField(default=0,verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_promotion'
        verbose_name = '页促销活动'
        verbose_name_plural = verbose_name

class IndexTypeGoodsBanner(BaseModel):
    '''首页分类商品展示模型类'''
    DISPLAY_TYPE_CHOICES=(
        (0,'标题'),
        (1,'图片')
    )

    type=models.ForeignKey('GoodsType',verbose_name='商品类型')
    sku = models.ForeignKey('GoodsSKU', verbose_name='商品SKU')
    display_type=models.SmallIntegerField(default=1,choices=DISPLAY_TYPE_CHOICES,verbose_name='展示形式')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'df_index_type_goods'
        verbose_name = '主页分类展示商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.type.name

dailyfresh/cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.conf import settings
from goods.models import *
from utils.user_util import LoginRequiredMixin
from django.contrib.auth import authenticate, login,logout
from django.views.generic import View


class CartAddView(View):
    print('CartAddView')
    '''购物车记录添加'''
    def post(self,request):
        '''购物车记录添加'''
        user=request.user
        if not user.is_authenticated():
            return JsonResponse({'res':0,'errmsg':'请先登录'})

        #接收数据
        sku_id=request.POST.get('sku_id')
        count = request.POST.get('count')


        #数据验证
        if not all([sku_id,count]):
            return JsonResponse({'res':1,'errmsg':'数据不完整'})

        #验证添加的商品数量
        try:
            count=int(count)
        except Exception as e:
            return JsonResponse({'res':2,'errmsg':'商品数目出错'})

        #验证商品是否存在
        try:
            sku=GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res':3,'errmsg':'商品不存在'})

        #业务处理：添加购物车记录
        conn=settings.REDIS_CONN
        cart_key='cart_%d'%user.id
        #先尝试获取sku_id的值 ->  hget cart_key 属性
        #如果sku_id在hash中不存在，hget返回None
        cart_count=conn.hget(cart_key,sku_id)
        if cart_count:
            #来家购物车中商品的数目
            count+=int(cart_count)

        #验证库存
        if count>sku.stock:
            return JsonResponse({'res':4,'errmsg':'库存不足'})

        #设置hash中sku_id对应的值
        #hset-> 如果sku_id已经存在，更新数据,如果sku_id不存在,添加数据
        conn.hset(cart_key,sku_id,count)

        #计算用户购物车商品的数目条
        total_count=get_cart_count(user)
        print(total_count)

        #反应应答
        return JsonResponse({'res':5,'total_count':total_count,'message':'添加成功'})

class CartCountView(View):
    '''异步获取购物车商品总数量'''
    def get(self,request):
        total_count=get_cart_count(request.user)
        return JsonResponse({'total_count':total_count})

class CartInfoView(View):
    '''购物车页面显示'''
    def get(self,request):
        '''显示'''
        #获取登录用户
        user=request.user
        #获取用户购物车中商品的信息
        conn = settings.REDIS_CONN
        cart_key = 'cart_%d' % user.id
        #{'商品id':商品数量,...}
        cart_dict = conn.hgetall(cart_key)

        skus=[]
        #保存用户购物车中商品的总数目和总价格
        total_count=0
        total_price=0
        #遍历获取商品的信息
        for sku_id,count in cart_dict.items():
            #根据商品的id获取商品的信息
            sku=GoodsSKU.objects.get(id=sku_id)
            #计算商品的小计
            amount=sku.price*int(count)
            #动态给sku对象增加一个属性amount,保存商品的小计
            sku.amount=amount
            #动态给sku对象增加一个属性count,保存购物车中对应的商品数量
            sku.count=count
            #添加
            skus.append(sku)

            #累计计算商品的总数目和总价格
            total_count+=int(count)
            total_price+=amount

        #组织上下文
        context = {
            'total_count': total_count,
            'total_price': total_price,
            'skus': skus,
        }
        #使用模板
        return render(request,'cart.html',context)

class CartUpdateView(View):
    '''购物车记录更新'''
    def post(self,request):
        #获取登录用户
        user=request.user
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据验证
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        # 验证添加的商品数量
        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})

        # 验证商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理：更新购物车记录
        conn = settings.REDIS_CONN
        cart_key = 'cart_%d' % user.id

        # 验证库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '库存不足'})

        # 设置hash中sku_id对应的值
        # hset-> 如果sku_id已经存在，更新数据,如果sku_id不存在,添加数据
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车商品的总件数
        total_count = get_cart_count(user)

        # 反应应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '更新成功'})


class CartDeleteView(View):
    '''购物车记录删除'''
    def post(self, request):
        # 获取登录用户
        user = request.user
        if not user.is_authenticated():
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')

        # 数据验证
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})

        # 验证商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 业务处理：删除购物车记录
        conn = settings.REDIS_CONN
        cart_key = 'cart_%d' % user.id

        #删除 hdel
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车商品的总件数
        total_count = get_cart_count(user)

        # 反应应答
        return JsonResponse({'res': 3, 'total_count': total_count, 'message': '删除成功'})


def get_cart_count(user):
    '''获取用户购物车购买的商品的数目'''

    #保存用户购物车中商品的总数目
    total_count=0

    if user.is_authenticated():
        #链接redis
        conn = settings.REDIS_CONN
        #key
        cart_key = 'cart_%d' % user.id
        #获取信息
        cart_dict=conn.hgetall(cart_key)

        #便利获取商品的信息
        for sku_id,count in cart_dict.items():
            total_count+=int(count)

    return total_count

dailyfresh/templates/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-首页</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="/user/loginout">退出登录</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="/user/login">登录</a>
					<span>|</span>
					<a href="/user/register">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user">用户中心</a>
					<span>|</span>
					<a href="/cart/info">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>

			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="#" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="search_con fl">
			<form action="/search" method="get">
				<input type="text" class="input_text fl" name="q" placeholder="搜索商品" value="{{ query }}">
				<input type="button" class="input_btn fr" name="" value="搜索">
			</form>
		</div>
		<div class="guest_cart fr">
			<a href="/cart/info" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<!--<li><a href="#model01" class="fruit">新鲜水果</a></li>-->
			{% for type in types %}
			   <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				{% for banner in goods_banners %}
				<li><a href="#"><img src="{{ banner.image.url}}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<!--<a href="#"><img src="/static/images/adv01.jpg"></a>-->
			<!--<a href="#"><img src="/static/images/adv02.jpg"></a>-->
			{% for promotion in promotion_banners %}
			   <a href="{{ promotion.url }}"><img src="{{ promotion.image.url }}"></a>
			{% endfor %}
		</div>
	</div>

	{% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
				<!--<a href="#">鲜芒</a>-->
				<!--<a href="#">加州提子</a>-->
				<!--<a href="#">亚马逊牛油果</a>-->
				{% for banner in type.title_banners %}
				   <a href="{% url 'goods:detail' goods_id=banner.sku.id %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="{% url 'goods:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/static/images/banner01.jpg"></div>
			<ul class="goods_list fl">
				<!--<li>-->
					<!--<h4><a href="#">草莓</a></h4>-->
					<!--<a href="#"><img src="http://192.168.12.189:9999/group1/M00/00/00/wKgMvVvNeQaAO4t1AAB-Dgqix1w4017053"></a>-->
					<!--<div class="prize">¥ 30.00</div>-->
				<!--</li>-->
				{% for banner in type.image_banners %}
				   <li>
						<h4><a href="{% url 'goods:detail' goods_id=banner.sku.id %}">{{ banner.sku.name }}</a></h4>
						<a href="{% url 'goods:detail' goods_id=banner.sku.id %}"><img src="{{ banner.sku.image.url }}"></a>
						<div class="prize">{{ banner.sku.price }}</div>
				   </li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}


	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	<script type="text/javascript" src="js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
</body>
</html>

dailyfresh/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-登录</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">日夜兼程 · 急速送达</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="/user/register">立即注册</a>
				</div>
				<div class="form_input">
					<form method="post" >
						{% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名" value="{{remember_username}}"/>
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<input name="validate_code" class="validate_code_input" placeholder="请输入验证码"/>
                        <img id='validate_code_img' src="{% url 'user:validate_code'%}" class="validate_code_img" />
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" value="1">
							<label>记住用户名</label>
							<a href="/user/change_passwd">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
				{{ error_name }}
			</div>
		</div>
	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>

<script>
    var validate_code_img=document.getElementById('validate_code_img')
    var url='/user/validate_code?num='
    validate_code_img.onclick=function () {
        var num=new Date().getTime()
        url+=num
        validate_code_img.src=url
    }
</script>

dailyfresh/templates/test_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
    {% for goodstype in goodstype_list %}
    <li>
        <ul>
            <li>{{ goodstype.name }}</li>
            <li><img src="{{ goodstype.image.url }}"></li>
        </ul>
    </li>
    {% endfor %}
</ul>

</body>
</html>

dailyfresh/templates/text1.html
<div class="person-data-place">
                <p>居住地:</p>
                <div id="city_4">
                        <select class="prov"></select>
                        <select class="city" disabled="disabled"></select>
                        <select class="dist" disabled="disabled"></select>
                </div>
</div>

dailyfresh/templates/user_center_info.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
					<span>|</span>
					<a href="/user/loginout">退出登录</a>
				</div>
				{% else %}
				<div class="login_btn fl">
					<a href="/user/login">登录</a>
					<span>|</span>
					<a href="/user/register">注册</a>
				</div>
				{% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="user_center_order.html">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/index" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" {% if page == '1' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" {% if page == '2' %}class="active"{% endif %}>· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" {% if page == '3' %}class="active"{% endif %}>· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
							{% if address %}
							   <li><span>联系方式：</span>{{ address.phone }}</li>
							   <li><span>联系地址：</span>{{ address.address }}</li>
							{% else %}
							   <li><span>联系方式：</span>无默认</li>
							   <li><span>联系地址：</span>无默认</li>
							{% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
						<!--<li>-->
							<!--<a href="detail.html"><img src="/static/images/goods/goods003.jpg"></a>-->
							<!--<h4><a href="detail.html">大兴大棚草莓</a></h4>-->
							<!--<div class="operate">-->
								<!--<span class="prize">￥16.80</span>-->
								<!--<span class="unit">16.80/500g</span>-->
								<!--<a href="#" class="add_goods" title="加入购物车"></a>-->
							<!--</div>-->
						<!--</li>-->
						{% for sku in goodskus %}
						   <li>
								<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
								<h4><a href="detail.html">{{ sku.name }}</a></h4>
								<div class="operate">
									<span class="prize">￥{{ sku.price }}</span>
									<span class="unit">{{ sku.price }}/{{ sku.unite }}</span>
									<a href="#" class="add_goods" title="加入购物车"></a>
								</div>
						   </li>
						{% endfor %}
					</ul>
				</div>
		</div>
	</div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>